version: '2'

services:
    web:
        build:
            context: ./APP-LB-RoundRobin
            dockerfile: Dockerfile
        container_name: web
        ports:
            - "8087:6000"
    log:
        build:
            context: ./Log-Service
            dockerfile: Dockerfile
        container_name: log_sv1
        ports:
            - "8090:6000"
    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config: